# pre-defined variables
server:
  port: 8081

# pre-defined variables
spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5432/db_bc2408"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
# Custom variables